backend:
  name: github
  repo: lekevoid/broadsign_ace_gatsby
  branch: master # Branch to update (optional; defaults to master)
  squash_merges: true

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "slides" # Used in routes, e.g., /admin/collections/blog
    label: "Slides" # Used in the UI
    folder: "slides" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
    - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Body", name: "body", widget: "markdown"}
    - label: "Image Gallery"
      name: "gallery"
      widget: "object"
      fields:
      - {label: "Image #1", name: "thumbnail_1", widget: "image", required: false}
      - {label: "Image #2", name: "thumbnail_2", widget: "image", required: false}
      - {label: "Image #3", name: "thumbnail_3", widget: "image", required: false}
    - label: "Categories"
      name: "categories"
      widget: "object"
      fields:
      - label: "Products"
        name: "products"
        widget: "object"
        fields:
        - {label: "Broadsign Control", name: "broadsign_control", widget: "boolean", default: false, required: false}
        - {label: "Broadsign Creator", name: "broadsign_creator", widget: "boolean", default: false, required: false}
        - {label: "Broadsign Direct", name: "broadsign_direct", widget: "boolean", default: false, required: false}
        - {label: "Broadsign Publish", name: "broadsign_publish", widget: "boolean", default: false, required: false}
        - {label: "Broadsign Reach", name: "broadsign_reach", widget: "boolean", default: false, required: false}
      - label: "Verticals"
        name: "verticals"
        widget: "object"
        fields:
        - {label: "Cinema", name: "cinema", widget: "boolean", default: false, required: false}
        - {label: "Gas Stations", name: "gas_stations", widget: "boolean", default: false, required: false}
        - {label: "Healthcare", name: "healthcare", widget: "boolean", default: false, required: false}
        - {label: "Hospitality", name: "hospitality", widget: "boolean", default: false, required: false}
        - {label: "Internal Comms", name: "internal_comms", widget: "boolean", default: false, required: false}
        - {label: "Outdoor", name: "outdoor", widget: "boolean", default: false, required: false}
        - {label: "Shopping Malls", name: "shopping_malls", widget: "boolean", default: false, required: false}
        - {label: "Smart Cities", name: "smart_cities", widget: "boolean", default: false, required: false}
        - {label: "Transit", name: "transit", widget: "boolean", default: false, required: false}