backend:
  name: github
  repo: lekevoid/broadsign_ace_gatsby
  branch: master # Branch to update (optional; defaults to master)
  squash_merges: true

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "slides" # Used in routes, e.g., /admin/collections/blog
    label: "Slides" # Used in the UI
    folder: "slides" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
    - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Body", name: "body", widget: "markdown"}
    - label: "Image Gallery"
      name: "gallery"
      widget: "object"
      fields:
      - {label: "Image #1", name: "thumbnail_1", widget: "image", required: false}
      - {label: "Image #2", name: "thumbnail_2", widget: "image", required: false}
      - {label: "Image #3", name: "thumbnail_3", widget: "image", required: false}
      - {label: "Image #4", name: "thumbnail_4", widget: "image", required: false}
      - {label: "Image #5", name: "thumbnail_5", widget: "image", required: false}
      - {label: "Image #6", name: "thumbnail_6", widget: "image", required: false}
      - {label: "Image #7", name: "thumbnail_7", widget: "image", required: false}
      - {label: "Image #8", name: "thumbnail_8", widget: "image", required: false}
      - {label: "Image #9", name: "thumbnail_9", widget: "image", required: false}
      - {label: "Image #10", name: "thumbnail_10", widget: "image", required: false}
    - label: "Categories"
      name: "categories"
      widget: "object"
      fields:
      - label: "Products"
        name: "products"
        widget: "select"
        multiple: true
        options:
        - {label: "Broadsign Control", value: "broadsign_control"}
        - {label: "Broadsign Creator", value: "broadsign_creator"}
        - {label: "Broadsign Direct", value: "broadsign_direct"}
        - {label: "Broadsign Publish", value: "broadsign_publish"}
        - {label: "Broadsign Reach", value: "broadsign_reach"}
      - label: "Verticals"
        name: "verticals"
        widget: "select"
        multiple: true
        options:
        - {label: "Cinema", value: "cinema"}
        - {label: "Gas Stations", value: "gas_stations"}
        - {label: "Healthcare", value: "healthcare"}
        - {label: "Hospitality", value: "hospitality"}
        - {label: "Internal Comms", value: "internal_comms"}
        - {label: "Outdoor", value: "outdoor"}
        - {label: "Shopping Malls", value: "shopping_malls"}
        - {label: "Smart Cities", value: "smart_cities"}
        - {label: "Transit", value: "transit"}